### PR TITLE
Increase logical CPU count

### PR DESCRIPTION
**Pull request by arunk1988**
**Description:** Updated BPF_MAX_CPUS

**Link to tracking Issue:** #258

### CODE REVIEW

**Comment by arunk1988** [comment]
Hi @yonch, Could you please review this PR

**Review by yonch — APPROVED** [review]

**Comment by yonch** [comment]
Hi @arunk1988 , this is approved. Sorry for how long this took. 

I do not have an Update Branch button on the UI, could you rebase / merge your branch on top of a recent `main`?

**Comment by arunk1988** [comment]
Hi @yonch , Thanks for approving, will work on rebase and update you shortly

**Comment by arunk1988** [comment]
Hi @yonch, I have rebased, please do the needful.

**Comment by yonch** [comment]
Done!
closes #258

**Pull request merged**
